fixed naming error
Seravo/wp-google-groups-subscribe pull request #4
Opened 2019-07-22 17:41 UTC by mitchnegus

I fixed the `PLUGIN_OBJ` name to match what is in `process.js`. This is what was intended by #3 (without all the Berkeley-specific changes).

2019-07-23 06:27 UTC, ypcs commented
Hi, thanks for the PR, I'll check this ASAP.

2020-04-27 05:57 UTC, ottok commented
@ypcs Please check this our before midsummer 2020.

2020-07-13 10:20 UTC, ypcs requested changes
Good fix, but due to policies we need to do "inverse" of this fix, ie. replace Google_Groups_Subscribe_AJAX elsewhere.

2020-07-13 10:20 UTC, ypcs commented on subscribe-google-groups.php
> +  const PLUGIN_OBJ = 'Google_Groups_Subscribe_AJAX';
Hi. Sorry that this has been pending so long.

We probably should replace `Google_Groups_Subscribe_AJAX` elsewhere with `Subscribe_Google_Groups_AJAX` as due to WordPress plugin repository policy we can't use trademark of someone else as the first part in name. For similar reason the whole plugin is named `WP Subscribe Google Groups` instead of `Google Groups Subscribe` or something.

Thank you, and my apologies.

2020-07-15 05:47 UTC, mitchnegus commented on subscribe-google-groups.php
> +  const PLUGIN_OBJ = 'Google_Groups_Subscribe_AJAX';
No problem, that makes sense. Fixed it!

2020-07-15 07:01 UTC, ypcs approved these changes
Looks good!

2020-07-15 07:01 UTC, merged